Repository RAF-SI-2023/Banka-3-Infrastructure, pull requests merged in 2024-05, with the labels that each got.

#7 Create OWNERS
  OWNERS
Labels: size/XS, do-not-merge/invalid-owners-file, lgtm

#6 Feat/kubernetes
  images/frontend.Dockerfile
  kubernetes/README.md
  kubernetes/bank-service.yaml
  kubernetes/email-service.yaml
  kubernetes/exchange-service.yaml
  kubernetes/frontend.yaml
  kubernetes/ingress.yaml
  kubernetes/namespaces.yaml
  kubernetes/postgres.yaml
  kubernetes/user-service.yaml
Labels: lgtm, size/L, approved

#8 Add redis and mongo
  docker-compose.yml
Labels: lgtm, size/S, approved

#9 Update docker-compose.yml
  docker-compose.yml
Labels: lgtm, size/S, approved
